### ISSUE TITLE
beta cookie version does't work

### ISSUE THREAD

**Issue by gilimotil** [LBBO/netflix-migrate#55]
I tried to import to my new netflix account and got this exception:

![image](https://user-images.githubusercontent.com/8076094/106630466-279eca00-657c-11eb-8562-f2c0230fe612.png)

**Comment by LBBO** [comment]
Hey @gilimotil,

thanks for reporting your issue! I took the liberty of censoring your screenshot to remove some potentially sensitive data. Remember, anyone with this cookie could be able to login to your account!

Once I have an update regarding the actual bug, I'll let you know.

**Comment by LBBO** [comment]
Ok @gilimotil , I'm not sure what is causing this issue. It looks like your command isn't being parsed as intended (note that netflix-migrate asked for your profile name, even though you provided it correctly. Additionally, the unrecognized commands are all strings that can be found in the cookie). However, I can't see anything wrong with your command (I even checked before censoring the screenshot and it looked fine).

Are you sure double quotes work in your cmd? Maybe try something like `cd "C:\Program Files"` and see if it works. After a quick Google search, I found this superuser article that seems to cover a similar (if not identical) issue: https://superuser.com/questions/1059582/double-quotes-not-working-on-windows-command-line

**Comment by gilimotil** [comment]
ok, I fix the quotes issue but still got an exception:

![image](https://user-images.githubusercontent.com/78433025/106642673-55dad480-6591-11eb-97d3-480fb7e7446e.png)

**Comment by LBBO** [comment]
I see you're now importing from a file. Did the export work? The "Inactive Account" error essentially means that authentication failed. It is still left over from the old email and password authentication and no longer has the same meaning.

Is the cookie you are using up to date? If it's a few hours old, maybe try and extract it again. Also, please make sure it contains both a `NetflixId` and a `SecureNetflixId`.

**Comment by gilimotil** [comment]
the export worked with the regular version, not the beta, so I have a valid JSON file on my computer.
The cookie is new, never had a cookie from the old mail...
I tried refresh the browser and exctract new cookie many times, still got the same exception

**Comment by gilimotil** [comment]
I tried export with the beta version and got the same exception...
Maybe I am doing something wrong, take the wrong cookie or something like that..

**Comment by gilimotil** [comment]
Did you find why I got the exception?
Thanks, 
Gili Motil

**Comment by LBBO** [comment]
No, not yet, I'm sorry. The error might be related to node, it might be related to your location...

Do you have any JavaScript programming experience and could help me gather some additional information? I'd be interested in testing some "custom requests" with your cookie to see if the cookie works at all and I'm also curious about some details about Netflix' response that causes the authorization to fail. I expect it to be their standard login page for when a user entered incorrect credentials, who knows -- your local Netflix version might be different than mine in that regard.

If you'd be willing to help, we could hop on a voice chat (i.e. Jitsi, but feel free to suggest something else) and we could have a go at figuring this out together.

**Comment by LBBO** [comment]
I just published a new beta version of node-netflix2 (a package that provides a JS interface for the Netflix API). If you re-execute the command, you should now find an `errorResponsePage.html` file in your current directory. Please open it in your browser and upload a screenshot of it (unless it contains any sensitive data, of course).

For reference, when I enter an outdated cookie, my response page looks like this (zoomed to fit the entire page):

![image](https://user-images.githubusercontent.com/8076094/106919342-5ba7f580-670a-11eb-9a09-33bb66981e3b.png)

I'd expect you to see the same sort of page, perhaps with your locale or something. If your result is significantly different, that might be what's causing your error.

**Comment by gilimotil** [comment]
I have some JavaScript experience but I don't have IDE at my home computer. Only ay my work place but I don't have access to the internet there...

We can make a zoom meeting, I don't have a problem..

**Comment by LBBO** [comment]
We won't need a full-blown IDE; a simple VS Code setup with node should do. You can contact me at mdk@kuckuk.com so that we can arrange the exact details of our meeting, but any actual discussion of the issue should continue to take place on this issue. That way, other users will be able to benefit from our discussion.

**Comment by ShizCalev** [comment]
Are you using a cookie taken from chrome? I noticed there is a difference as chrome doesn't sanitize " 's, resulting in cookies grabbed from it not working vs cookies taken from firefox with sanitizes as %22

**Comment by LBBO** [comment]
That actually depends on how you extract the cookie from Chrome (for me, at least). The way you should do it is by manually selecting the entire string with your mouse and pressing Ctrl + C. For me, this consistently gives me the correct cookie without any quotes.

If, instead, you right-click the cookie and click on "Copy Value", Chrome will decode the cookie and will turn `%22` back into `"`.

I'll make sure to clarify how to extract the cookie in the README.

**Comment by mcdado** [comment]
I managed to make it work by coping out the cookie from the headers in the Network panel. But does the v2 version only import ratings or also viewing history?

**Comment by lcdss** [comment]
I successfully exported two profiles from my Netflix account this last weekend using the branch `cookie-login`. For a moment I thought the profile export feature isn't working, since both profiles had the same data, but was my mistake by using the same cookie for both profiles.

Thanks @LBBO for building this tool.

**Comment by LBBO** [comment]
@mcdado Sadly, I haven't been able to make importing viewing history work. The data can already be exported (i.e. downloaded) but the import seems to be far more difficult. Since you have the data, though, you should hopefully be able to just import it if and when the feature is added. For more information on this feature, please refer to #31.

@lcdss I'm glad you were able to resolve the issue and the tool was able to help you!

@gilimotil Is there any update on your problems? If you don't say otherwise, I'll consider them resolved in a few days / weeks / whenever I do some housekeeping 😅

**Comment by Chewbacca222222** [comment]
I'm still getting the issue first mentioned, I've tried both importing and exporting using the standard and the cookie edition and the only thing that has worked so far is the export of the standard (non-cookie edition). I've attached the output below of the commands and I've followed the instructions in the readme (make sure there are no quote marks e.t.c). Thanks in advance and awesome package btw!!!
```
npx netflix-migrate --cookie "[[MY_COOKIE_DATA]]" --import netflixData.json
Profile name. Please pay special attention to spelling!: [[PROFILE]]
Using new Netflix2 class!
Logging into Netflix using Cookies
Error: Inactive account
    at Netflix.__getContextData (C:\Users\joebloggs\Desktop\Netflix migrate 2\node_modules\netflix2\lib\netflix2.js:555:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Netflix.__getContextDataFromUrls (C:\Users\joebloggs\Desktop\Netflix migrate 2\node_modules\netflix2\lib\netflix2.js:594:7)
    at async Netflix.login (C:\Users\joebloggs\Desktop\Netflix migrate 2\node_modules\netflix2\lib\netflix2.js:76:9)
    at async main (C:\Users\joebloggs\Desktop\Netflix migrate 2\node_modules\netflix-migrate\main.js:24:3)
The exact response HTML file was saved to C:\Users\joebloggs\Desktop\Netflix migrate 2\errorResponsePage.html
Error: There was a problem fetching user data. For more information, see previous log statements.
    at Netflix.__getContextData (C:\Users\joebloggs\Desktop\Netflix migrate 2\node_modules\netflix2\lib\netflix2.js:584:13)
    at async Netflix.__getContextDataFromUrls (C:\Users\joebloggs\Desktop\Netflix migrate 2\node_modules\netflix2\lib\netflix2.js:594:7)
    at async Netflix.login (C:\Users\joebloggs\Desktop\Netflix migrate 2\node_modules\netflix2\lib\netflix2.js:76:9)
    at async main (C:\Users\joebloggs\Desktop\Netflix migrate 2\node_modules\netflix-migrate\main.js:24:3)
Error: Something went wrong. For more information, see previous log statements.
    at Netflix.login (C:\Users\joebloggs\Desktop\Netflix migrate 2\node_modules\netflix2\lib\netflix2.js:88:13)
'datestamp' is not recognized as an internal or external command,
operable program or batch file.
'version' is not recognized as an internal or external command,
operable program or batch file.
'consentId' is not recognized as an internal or external command,
operable program or batch file.
'interactionCount' is not recognized as an internal or external command,
operable program or batch file.
'landingPath' is not recognized as an internal or external command,
operable program or batch file.
groups: ‘=[[SECRET_VALUE]]’: no such user
'hosts' is not recognized as an internal or external command,
operable program or batch file.
'AwaitingReconsent' is not recognized as an internal or external command,
operable program or batch file.
'geolocation' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by quophyie** [comment]
I am having the exact same problem as @Chewbacca222222

**Comment by danypacf** [comment]
Account must be active.

**Comment by Chewbacca222222** [comment]
> Account must be active.

Both accounts were active, I tried on multiple occasions too.

**Comment by Cyril035** [comment]
Hi there,

I try to use this beta version and same pb

![image](https://user-images.githubusercontent.com/20580881/147751652-fd4b6b07-a95c-4bc6-b367-c0004a6a87e8.png)

I precise that my account is well active. How can I help you for testing/resolve this ?

**Comment by LBBO** [comment]
Hey everyone! Sorry for not helping out with this issue for so long, I was just really busy and, quite frankly, fed up with playing catchup with changes to Netflix's API or DOM structure or whatever every couple of months.

However, there's some good news! In case anyone hasn't heard, Netflix now officially supports account migration, including viewing history! For more details, see their [official documentation](https://help.netflix.com/en/node/124844). Since that feature implements exactly what this project was aiming to do, I will officially archive this repository now (see #73). Feel free to reach out if you have any further questions!

(Also, on a side note @Cyril035: your cookie doesn't look right. That looks like a UUID but the cookie information should have been some huge string similar to `key1=value1; key2=value2`. Just in case you need to extract a cookie some time again 😉)
